## All playbooks
ansible_python_interpreter: ""
domain_suffix: ""
# For now DPDK / Kernel / SRIOV VMs all need to be on separate compute nodes
dpdk_nodes: ["172.16.0.55"]
sriov_nodes: [""]
kernel_nodes: ["172.16.0.55"]
# use 998 for production
sriov_vlan: "xxx"
sriov_ip_start: "1.1.1.0/24"
sriov_leak_rt: "target:x:x" 
glance_image_url: ""
# use below for failover testing
contrail_server: "1.1.1.1"
## VM Testing playbooks
ssh_id_location: "vm-key.pub"
ssh_private_key_location: "vm-key"
ssh_remote_dir: "/home/ubuntu"
introspect_cert: ""
introspect_key: ""
# These playbooks currently don't support uploading an image to Glance so we need to use one already deployed
#vm_image: "ubuntu-bionic"
vm_image: "Bionic_Ubuntu"   

## API Testing playbooks
api_url: "https://172.16.0.100:8082"
