# All
ansible_python_interpreter: "/home/vernald2/git-clones/scratch3/venvs/portable/bin/python"
script_dir: "/home/vernald2/git-clones/bt-repo/ansible-NATP"
management_net: "natp-management-net"
domain: "int"
project: "ref_uat"
domain_suffix: "002.ncitest.bt.com"
dpdk_node: "b26nc01node013"
kernel_node: "b26nc01node011"
sriov_node: "b26nc01node010"
glance_image_url: ""
rc_file: "~/fordanny/adstrc-int"
# VM Testing
ssh_id_location: "vm-key.pub"
ssh_private_key_location: "vm-key"
ssh_remote_dir: "/home/ubuntu"
introspect_cert: "/home/vernald2/git-clones/bt-repo/contrail-introspect-cli/certs/Jump002-Gemini.pem"
introspect_key: "/home/vernald2/git-clones/bt-repo/contrail-introspect-cli/certs/Jump002-Gemini_no_pwd.key"

# API Testing
api_url: "https://contrailapi.002.ncitest.bt.com:8082"
