---
- name: Test Connectivity on VMs via Metadata IPs 
  hosts: VMS
  vars:
    results_dir: "{{ script_dir }}/output"
  tasks:
    - name: Copy SSH Key To Compute Nodes
      copy:
        src: "{{ ssh_private_key_location }}"
        dest: "{{ ssh_remote_dir }}/vm-key"
        owner: ubuntu
        group: ubuntu
        mode: 0600
    - name: Ping Test VMs
      include_tasks: ./ping_includes.yaml
      with_items: "{{ vms }}"
      loop_control:
        loop_var: vm

