---
    - name: Check SSH known_hosts for {{ inventory_hostname }}
      local_action: shell ssh-keygen -F {{ inventory_hostname }}
      register: checkForKnownHostsEntry
      failed_when: false
      changed_when: false
      ignore_errors: yes
    - name: Add {{ inventory_hostname }} to SSH known hosts automatically
      when: checkForKnownHostsEntry.rc == 1
      changed_when: checkForKnownHostsEntry.rc == 1
      set_fact:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    - name: Copy SSH Key To Compute Nodes
      copy:
        src: "{{ ssh_private_key_location }}"
        dest: "{{ ssh_remote_dir }}/vm-key"
        owner: ubuntu
        group: ubuntu
        mode: 0600

