domain: "{{ lookup('env','OS_PROJECT_DOMAIN_NAME') }}" 
project:  "{{ lookup('env','OS_PROJECT_NAME') }}"
remote_env:
  OS_AUTH_URL: "{{ lookup('env','OS_AUTH_URL') }}"
  OS_ENDPOINT_TYPE: "{{ lookup('env','OS_ENDPOINT_TYPE') }}"
  OS_REGION_NAME: "{{ lookup('env','OS_REGION_NAME') }}"
  OS_PROJECT_NAME: "{{ lookup('env','OS_PROJECT_NAME') }}"
  OS_PROJECT_DOMAIN_NAME: "{{ lookup('env','OS_PROJECT_DOMAIN_NAME') }}"
  OS_USER_DOMAIN_NAME: "{{ lookup('env','OS_USER_DOMAIN_NAME') }}"
  OS_AUTH_VERSION: "{{ lookup('env','OS_AUTH_VERSION') }}"
  OS_IDENTITY_API_VERSION: "{{ lookup('env','OS_IDENTITY_API_VERSION') }}"
  OS_INTERFACE: "{{ lookup('env','OS_INTERFACE') }}"
  OS_PASSWORD: "{{ lookup('env','OS_PASSWORD') }}"
  OS_USERNAME: "{{ lookup('env','OS_USERNAME') }}"
  OS_CACERT: "{{ lookup('env','OS_CACERT') }}"
