---
# Test that Contrail API is working and correct objects exist from the instantiated 
# heat stacks.
# JSON data for the objects can be read with e.g. 'jq . ./output/vn_kernel'
#
# This is dependent on openstack cloud module
# https://docs.ansible.com/ansible/latest/collections/openstack/cloud/auth_module.html

    - name: Authenticate to OpenStack
      openstack.cloud.auth:
      register: os_auth_results
    - name: Base API check
      uri:
        url: "{{ api_url }}"
    - name: Get Kernel VN UUID
      uri:
        url: "{{ api_url }}/fqname-to-id"
        method: POST
        return_content: yes
        headers:
          X-Auth-Token: "{{ os_auth_results.ansible_facts.auth_token }}"
          Content-Type: "application/json; charset=UTF-8"
        body_format: json
        body: "{\"fq_name\": [\"{{ domain }}\", \"{{ project }}\", \"natp-kernel-net\"], \"type\": \"virtual-network\"}"
      register: vn_kernel_uuid
    - name: Get Kernel VN
      uri:
        url: "{{ api_url }}/virtual-network/{{vn_kernel_uuid.json.uuid}}"
        method: GET
        return_content: yes
        headers:
          X-Auth-Token: "{{ os_auth_results.ansible_facts.auth_token }}"
          Content-Type: "application/json; charset=UTF-8"
      register: vn_kernel_json
    - name: "Saving API reply to disk (./output)"  
      local_action: copy content={{ vn_kernel_json.json }} dest="{{results_dir}}/vn_kernel.json"
    - name: Get Kernel VMs
      uri:
        url: "{{ vn_kernel_json.json[\"virtual-network\"][\"virtual_machine_interface_back_refs\"][kern_idx][\"href\"] }}"
        method: GET
        return_content: yes
        headers:
          X-Auth-Token: "{{ os_auth_results.ansible_facts.auth_token }}"
          Content-Type: "application/json; charset=UTF-8"
      loop: "{{ kernel_nodes }}"
      loop_control:
        index_var: kern_idx
      register: vm_kernel_json
    - name: "Saving API reply to disk (./output)"
      local_action: copy content={{ vm_kernel_json }} dest="{{results_dir}}/vm_kernel.json"
    - name: Get DPDK VN UUID
      uri:
        url: "{{ api_url }}/fqname-to-id"
        method: POST
        return_content: yes
        headers:
          X-Auth-Token: "{{ os_auth_results.ansible_facts.auth_token }}"
          Content-Type: "application/json; charset=UTF-8"
        body_format: json
        body: "{\"fq_name\": [\"{{ domain }}\", \"{{ project }}\", \"natp-dpdk-net\"], \"type\": \"virtual-network\"}"
      register: vn_dpdk_uuid
    - name: Get DPDK VN
      uri:
        url: "{{ api_url }}/virtual-network/{{vn_dpdk_uuid.json.uuid}}"
        method: GET
        return_content: yes
        headers:
          X-Auth-Token: "{{ os_auth_results.ansible_facts.auth_token }}"
          Content-Type: "application/json; charset=UTF-8"
      register: vn_dpdk_json
    - name: "Saving API reply to disk (./output)"
      local_action: copy content={{ vn_dpdk_json.json }} dest="{{results_dir}}/vn_dpdk.json"
    - name: Get SRIOV VN UUID
      uri:
        url: "{{ api_url }}/fqname-to-id"
        method: POST
        return_content: yes
        headers:
          X-Auth-Token: "{{ os_auth_results.ansible_facts.auth_token }}"
          Content-Type: "application/json; charset=UTF-8"
        body_format: json
        body: "{\"fq_name\": [\"{{ domain }}\", \"{{ project }}\", \"natp-physnet_1_network\"], \"type\": \"virtual-network\"}"
      register: vn_sriov_uuid
    - name: Get SRIOV VN
      uri:
        url: "{{ api_url }}/virtual-network/{{vn_sriov_uuid.json.uuid}}"
        method: GET
        return_content: yes
        headers:
          X-Auth-Token: "{{ os_auth_results.ansible_facts.auth_token }}"
          Content-Type: "application/json; charset=UTF-8"
      register: vn_sriov_json
    - name: "Saving API reply to disk (./output)"
      local_action: copy content={{ vn_sriov_json.json }} dest="{{results_dir}}/vn_sriov.json"
    - name: Get DPDK VMs
      uri:
        url: "{{ vn_dpdk_json.json[\"virtual-network\"][\"virtual_machine_interface_back_refs\"][dpdk_idx][\"href\"] }}"
        method: GET
        return_content: yes
        headers:
          X-Auth-Token: "{{ os_auth_results.ansible_facts.auth_token }}"
          Content-Type: "application/json; charset=UTF-8"
      loop: "{{ dpdk_nodes }}"
      loop_control:
        index_var: dpdk_idx
      register: vm_dpdk_json
    - name: "Saving API reply to disk (./output)"
      local_action: copy content={{ vm_dpdk_json }} dest="{{results_dir}}/vm_dpdk.json"
    - name: Get SRIOV VMs
      uri:
        url: "{{ vn_sriov_json.json[\"virtual-network\"][\"virtual_machine_interface_back_refs\"][sriov_idx][\"href\"] }}"
        method: GET
        return_content: yes
        headers:
          X-Auth-Token: "{{ os_auth_results.ansible_facts.auth_token }}"
          Content-Type: "application/json; charset=UTF-8"
      loop: "{{ sriov_nodes }}"
      loop_control:
        index_var: sriov_idx
      register: vm_sriov_json
    - name: "Saving API reply to disk (./output)"
      local_action: copy content={{ vm_sriov_json }} dest="{{results_dir}}/vm_sriov.json"
    - name: Get Network Policy UUID
      uri:
        url: "{{ api_url }}/fqname-to-id"
        method: POST
        return_content: yes
        headers:
          X-Auth-Token: "{{ os_auth_results.ansible_facts.auth_token }}"
          Content-Type: "application/json; charset=UTF-8"
        body_format: json
        body: "{\"fq_name\":[\"{{ domain }}\", \"{{ project }}\", \"natp-test-policy\"], \"type\": \"network-policy\"}"
      register: network_policy_uuid
    - name: Get Network Policy
      uri:
        url: "{{ api_url }}/network-policy/{{network_policy_uuid.json.uuid}}"
        method: GET
        return_content: yes
        headers:
          X-Auth-Token: "{{ os_auth_results.ansible_facts.auth_token }}"
          Content-Type: "application/json; charset=UTF-8"
      register: network_policy_json
    - name: "Saving API reply to disk (./output)"
      local_action: copy content={{ network_policy_json.json }} dest="{{results_dir}}/network_policy.json"
    - name: Get Security Group UUID
      uri:
        url: "{{ api_url }}/fqname-to-id"
        method: POST
        return_content: yes
        headers:
          X-Auth-Token: "{{ os_auth_results.ansible_facts.auth_token }}"
          Content-Type: "application/json; charset=UTF-8"
        body_format: json  
        body: "{\"fq_name\": [\"{{ domain }}\", \"{{ project }}\", \"natp-test-sec-group\"], \"type\": \"security-group\"}"
      register: security_group_uuid
    - name: Get Security Group
      uri:
        url: "{{ api_url }}/security-group/{{security_group_uuid.json.uuid}}"
        method: GET
        return_content: yes
        headers:
          X-Auth-Token: "{{ os_auth_results.ansible_facts.auth_token }}"
          Content-Type: "application/json; charset=UTF-8"
      register: security_group_json
    - name: "Saving API reply to disk (./output)"
      local_action: copy content={{ security_group_json.json }} dest="{{results_dir}}/security_group.json"
