heat_template_version: queens
resources:
        
  nova_flavor:
    type: OS::Nova::Flavor
    properties:
      is_public: true
      name: natp.xp.m1.small
      ram: 2048
      vcpus: 2 
      disk: 10


