heat_template_version: queens
parameters:
  vdns: 
    type: string
    default: "natp-test-vdns"
  fq_string:
    type: string
    description: fq_string for the VDNS
    default: "admin_domain:admin"
resources:
  test_ipam:
    type: OS::ContrailV2::NetworkIpam
    properties:
      name: natp-test-ipam
      virtual_DNS_refs: [{list_join: [':', [ {get_param: fq_string}, {get_param: vdns}]]} ]
      network_ipam_mgmt:
          network_ipam_mgmt_ipam_dns_method: "virtual-dns-server"
          network_ipam_mgmt_ipam_dns_server:
              network_ipam_mgmt_ipam_dns_server_virtual_dns_server_name: {list_join: [':', [ {get_param: fq_string}, {get_param: vdns}]]} 
          network_ipam_mgmt_dhcp_option_list:
              network_ipam_mgmt_dhcp_option_list_dhcp_option:
                      - { network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_name:  "26",
                        network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_value: "9000" }   
        
