heat_template_version: queens

parameters:
   fq_string:
    type: string
    default: "admin_domain:admin"

   vn_ipam:
    type: string
    default: "natp-physnet_1_ipam"

resources:
        
  physnet_1_network:
    type: OS::ContrailV2::VirtualNetwork
    properties:
      name: "natp-physnet_1_network"
      provider_properties:
        {
          provider_properties_segmentation_id: 1001,
          provider_properties_physical_network: physnet_sriov1,
        }
      network_ipam_refs: [{list_join: [':', [ {get_param: fq_string}, {get_param: vn_ipam}]]}]
      network_ipam_refs_data:
        [
          {
            network_ipam_refs_data_ipam_subnets:
              [
                {
                  network_ipam_refs_data_ipam_subnets_subnet:
                    {
                      network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: "192.168.112.0",
                      network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: "24",
                    },
                  network_ipam_refs_data_ipam_subnets_addr_from_start: "true",
                  network_ipam_refs_data_ipam_subnets_enable_dhcp: "false",
                },
              ],
          },
        ]
